Write a NumPy program to count a given word in each row of a given array of string values.

Sample output:

Original array of string values:

[['Python' 'NumPy' 'Exercises']
['Python' 'Pandas' 'Exercises']
['Python' 'Machine learning' 'Python']]

Count 'Python' row wise in the above array of string values:

[[1 0 0]
[1 0 0]
[1 0 1]]

In [2]:
import numpy as np
a = np.array([['Python', 'NumPy', 'Exercises'],
['Python', 'Pandas', 'Exercises'],
['Python', 'Machine learning', 'Python']])
print(np.char.count(a, 'Python'))

[[1 0 0]
 [1 0 0]
 [1 0 1]]
