## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import pandas as pd
import scipy as sp

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(loc = 100 , scale = 15, size = 1000)
np.set_printoptions(threshold=10)
samples

array([107.69561834, 106.11265274,  89.94412864, ...,  93.41035069,
        85.2098711 , 107.05262169])

Compute the **mean**, **median**, and **mode**

In [3]:
from scipy import stats

mean =samples.mean()
median =np.median(samples)
mode = stats.mode(samples)
print(" mean : ", mean,"\n", "median : ", median, "\n","mode : ", mode)

 mean :  100.29144062432452 
 median :  100.16901360255505 
 mode :  ModeResult(mode=array([50.87256793]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [6]:
min = samples.min()
max = samples.max()
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3- q1
print("min :" , min,
      "\nmax :",  max,
      "\nq1  :",   q1,
      "\nq3  :",  q3,
      "\niqr :",  iqr)


min : 50.87256792767105 
max : 148.79929149110856 
q1  : 89.96845031178725 
q3  : 111.02558180125361 
iqr : 21.057131489466357


Compute the **variance** and **standard deviation**

In [7]:
variance = np.var(samples)
std_dev = np.std(samples)
print("Variance : " , variance , "\nstd_dev : ", std_dev)

Variance :  234.33451719167314 
std_dev :  15.307988672313327


Compute the **skewness** and **kurtosis**

In [8]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print("skewness :", skewness,"\nkurtosis :", kurtosis)

skewness : -0.08084830919674786 
kurtosis : -0.1421271240264237


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [9]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [10]:
y = np.array(np.random.randint(20,size=10))
y

array([13,  4, 19, 19, 17,  8, 15,  7,  9, 12])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [11]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.19299671],
       [-0.19299671,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [12]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [13]:
r = x.corr(y)
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [15]:
rho =x.corr(y, method ="spearman")
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [16]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [18]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [19]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [21]:
tip=tips["tip"]
size=tips["size"]
r_corr =tip.corr(size)
r_corr

0.4892987752303577