In [1]:
import numpy as np

In [2]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
np.ones((4,4), dtype = int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [5]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [7]:
np.arange(0,18,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [9]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
np.linspace(0,25,25).reshape(5,5)

array([[ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667],
       [ 5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ],
       [10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333],
       [15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667],
       [20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ]])

In [17]:
np.linspace(0, 25, 25, endpoint = False).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [5]:
import numpy as np
a= np.random.rand(0,1)
a

0

In [38]:
np.random.rand(5,5)

array([[0.836246  , 0.94905506, 0.35768269, 0.49861327, 0.88085129],
       [0.31631859, 0.9185775 , 0.98176695, 0.91377944, 0.22564603],
       [0.15417348, 0.41671712, 0.99702183, 0.42829524, 0.35755381],
       [0.85583892, 0.40512361, 0.47357558, 0.77522099, 0.22237292],
       [0.0045089 , 0.54094849, 0.050314  , 0.27934575, 0.36719139]])

In [39]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


In [48]:
np.random.rand(5)


array([0.10002563, 0.11041942, 0.13876738, 0.28018819, 0.81671207])

In [49]:
np.random.randint(20, 50, size=(3, 4))

array([[34, 46, 40, 23],
       [27, 37, 49, 33],
       [25, 24, 49, 21]])

In [51]:
ranarr = np.random.randint(0, 60, 48).reshape(6,8)
ranarr

array([[45, 11, 44, 48, 30, 32, 19, 57],
       [33, 11, 17,  4, 15, 51, 32,  0],
       [46, 40, 23, 48, 35, 54, 23, 44],
       [ 0, 19, 21, 23, 24, 43, 32, 16],
       [40, 45, 55, 52, 38, 10, 38, 22],
       [ 8, 17, 33,  9, 38, 33, 15, 32]])

In [57]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
a [1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [60]:
a[:,0]

array([ 1,  5,  9, 13])

In [71]:
a[1,::2]

array([5, 7])

In [72]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
a[:,2] = 77
a

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [74]:
Take 1st row 0 column, 3th row 2nd column.

SyntaxError: invalid syntax (<ipython-input-74-37636346100d>, line 1)

In [77]:
a

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [87]:
a[[1,0],[3,2]]

array([ 8, 77])

In [86]:
a[1,0]

5

In [96]:
a[1::2,::2]

array([[ 5, 77],
       [13, 77]])

In [107]:
np.median(a[:,3])

10.0

In [102]:
np.std(a[:,3])

4.47213595499958

In [105]:
np.std(a)


30.004166377354995

In [106]:
np.sum(a[:,2])

308

In [110]:
abc = a[(a<10)]
abc

array([1, 2, 4, 5, 6, 8, 9])

In [112]:
abc2 = a[(a>12)]
abc2

array([77, 77, 77, 13, 14, 77, 16])

In [114]:
abc3 = abc + abc2
abc3

array([78, 79, 81, 18, 20, 85, 25])

In [9]:
import pandas as pd

In [11]:
df=pd.read_csv("Salaries.csv")
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [27]:
df[[2],["TotalPayBenefits"]]

TypeError: '([2], ['TotalPayBenefits'])' is an invalid key

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [126]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [137]:
df["TotalPay"].max()

567595.43

In [146]:
df["Year"].unique().tolist()


[2011, 2012, 2013, 2014]

In [152]:
df["TotalPay"].mean()

74768.321971703

In [158]:
len(df[df.TotalPay > df["TotalPay"].mean()])

69489

In [159]:
import seaborn as sns
import pandas as pd
import numpy as np

In [160]:
np.random.seed(42)
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split()          )
df3

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [162]:
df3.reset_index()

index         W         X         Y         Z
0     A  0.496714 -0.138264  0.647689  1.523030
1     B -0.234153 -0.234137  1.579213  0.767435
2     C -0.469474  0.542560 -0.463418 -0.465730
3     D  0.241962 -1.913280 -1.724918 -0.562288
4     E -1.012831  0.314247 -0.908024 -1.412304

In [163]:
df3.reset_index(drop=True)

W         X         Y         Z
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304

In [164]:
df3

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [165]:
df3.reset_index(drop=True, inplace=True)

In [166]:
df3

W         X         Y         Z
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304

In [167]:
new_index = np.arange(1000,1005)
new_index

array([1000, 1001, 1002, 1003, 1004])

In [168]:
df3["new_index"] = new_index
df3

W         X         Y         Z  new_index
0  0.496714 -0.138264  0.647689  1.523030       1000
1 -0.234153 -0.234137  1.579213  0.767435       1001
2 -0.469474  0.542560 -0.463418 -0.465730       1002
3  0.241962 -1.913280 -1.724918 -0.562288       1003
4 -1.012831  0.314247 -0.908024 -1.412304       1004

In [169]:
df3.set_index("new_index")

W         X         Y         Z
new_index                                        
1000       0.496714 -0.138264  0.647689  1.523030
1001      -0.234153 -0.234137  1.579213  0.767435
1002      -0.469474  0.542560 -0.463418 -0.465730
1003       0.241962 -1.913280 -1.724918 -0.562288
1004      -1.012831  0.314247 -0.908024 -1.412304

In [171]:
df3.set_index("new_index", inplace=True)
df3

W         X         Y         Z
new_index                                        
1000       0.496714 -0.138264  0.647689  1.523030
1001      -0.234153 -0.234137  1.579213  0.767435
1002      -0.469474  0.542560 -0.463418 -0.465730
1003       0.241962 -1.913280 -1.724918 -0.562288
1004      -1.012831  0.314247 -0.908024 -1.412304

In [172]:
df3.corr()

W         X         Y         Z
W  1.000000 -0.579383  0.162034  0.743211
X -0.579383  1.000000  0.409461 -0.011964
Y  0.162034  0.409461  1.000000  0.764853
Z  0.743211 -0.011964  0.764853  1.000000

In [173]:
new_index = ["MX", "MY", "MZ", "MW","MT"]

In [174]:
df3["col1"]=new_index
df3

W         X         Y         Z col1
new_index                                             
1000       0.496714 -0.138264  0.647689  1.523030   MX
1001      -0.234153 -0.234137  1.579213  0.767435   MY
1002      -0.469474  0.542560 -0.463418 -0.465730   MZ
1003       0.241962 -1.913280 -1.724918 -0.562288   MW
1004      -1.012831  0.314247 -0.908024 -1.412304   MT

In [175]:
df3.set_index("col1", inplace=True)
df3

W         X         Y         Z
col1                                        
MX    0.496714 -0.138264  0.647689  1.523030
MY   -0.234153 -0.234137  1.579213  0.767435
MZ   -0.469474  0.542560 -0.463418 -0.465730
MW    0.241962 -1.913280 -1.724918 -0.562288
MT   -1.012831  0.314247 -0.908024 -1.412304

In [177]:
df3.columns = ["X1","X2","X3","Result"]
df3

X1        X2        X3    Result
col1                                        
MX    0.496714 -0.138264  0.647689  1.523030
MY   -0.234153 -0.234137  1.579213  0.767435
MZ   -0.469474  0.542560 -0.463418 -0.465730
MW    0.241962 -1.913280 -1.724918 -0.562288
MT   -1.012831  0.314247 -0.908024 -1.412304

In [178]:
flights = sns.load_dataset("flights")
flights

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [179]:
flights.groupby("year").count()

month  passengers
year                   
1949     12          12
1950     12          12
1951     12          12
1952     12          12
1953     12          12
1954     12          12
1955     12          12
1956     12          12
1957     12          12
1958     12          12
1959     12          12
1960     12          12

In [180]:
flights.groupby("year").max()

passengers
year            
1949         148
1950         170
1951         199
1952         242
1953         272
1954         302
1955         364
1956         413
1957         467
1958         505
1959         559
1960         622

In [181]:
flights[flights.year ==1949]

year month  passengers
0   1949   Jan         112
1   1949   Feb         118
2   1949   Mar         132
3   1949   Apr         129
4   1949   May         121
5   1949   Jun         135
6   1949   Jul         148
7   1949   Aug         148
8   1949   Sep         136
9   1949   Oct         119
10  1949   Nov         104
11  1949   Dec         118

In [182]:
planets = sns.load_dataset("planets")
planets

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [183]:
planets.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [184]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [185]:
planets.describe(include="all")

method       number  orbital_period        mass     distance  \
count              1035  1035.000000      992.000000  513.000000   808.000000   
unique               10          NaN             NaN         NaN          NaN   
top     Radial Velocity          NaN             NaN         NaN          NaN   
freq                553          NaN             NaN         NaN          NaN   
mean                NaN     1.785507     2002.917596    2.638161   264.069282   
std                 NaN     1.240976    26014.728304    3.818617   733.116493   
min                 NaN     1.000000        0.090706    0.003600     1.350000   
25%                 NaN     1.000000        5.442540    0.229000    32.560000   
50%                 NaN     1.000000       39.979500    1.260000    55.250000   
75%                 NaN     2.000000      526.005000    3.040000   178.500000   
max                 NaN     7.000000   730000.000000   25.000000  8500.000000   

               year  
count   1035.000000  
unique          NaN  
top             NaN  
freq            NaN  
mean    2009.070531  
std        3.972567  
min     1989.000000  
25%     2007.000000  
50%     2010.000000  
75%     2012.000000  
max     2014.000000

In [187]:
planets.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [190]:
planets.method.describe()

count                1035
unique                 10
top       Radial Velocity
freq                  553
Name: method, dtype: object

In [191]:
planets["method"].value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

In [192]:
planets.groupby("method").sum()

number  orbital_period        mass   distance  \
method                                                                         
Astrometry                          2    1.262360e+03     0.00000      35.75   
Eclipse Timing Variations          15    4.276480e+04    10.25000    1261.44   
Imaging                            50    1.418973e+06     0.00000    2166.91   
Microlensing                       27    2.207500e+04     0.00000   41440.00   
Orbital Brightness Modulation       5    2.127920e+00     0.00000    2360.00   
Pulsar Timing                      11    3.671511e+04     0.00000    1200.00   
Pulsation Timing Variations         1    1.170000e+03     0.00000       0.00   
Radial Velocity                   952    4.553151e+05  1341.65638   27348.11   
Transit                           776    8.377523e+03     1.47000  134242.77   
Transit Timing Variations           9    2.393505e+02     0.00000    3313.00   

                                  year  
method                                  
Astrometry                        4023  
Eclipse Timing Variations        18090  
Imaging                          76347  
Microlensing                     46225  
Orbital Brightness Modulation     6035  
Pulsar Timing                     9992  
Pulsation Timing Variations       2007  
Radial Velocity                1110158  
Transit                         798461  
Transit Timing Variations         8050

In [197]:
planets.groupby(     "method"    )[["distance"]].sum()

distance
method                                  
Astrometry                         35.75
Eclipse Timing Variations        1261.44
Imaging                          2166.91
Microlensing                    41440.00
Orbital Brightness Modulation    2360.00
Pulsar Timing                    1200.00
Pulsation Timing Variations         0.00
Radial Velocity                 27348.11
Transit                        134242.77
Transit Timing Variations        3313.00

In [199]:
planets.groupby(     ["method", "year"]    )[["distance", "mass"]].sum()

distance  mass
method                    year                
Astrometry                2010     14.98  0.00
                          2013     20.77  0.00
Eclipse Timing Variations 2008    261.44  0.00
                          2009      0.00  6.05
                          2010   1000.00  0.00
...                                  ...   ...
Transit                   2014   2070.00  0.00
Transit Timing Variations 2011   2119.00  0.00
                          2012    855.00  0.00
                          2013    339.00  0.00
                          2014      0.00  0.00

[69 rows x 2 columns]

In [200]:
planets.groupby(     ["method", "year"]    ).sum()

number  orbital_period  mass  distance
method                    year                                        
Astrometry                2010       1     1016.000000  0.00     14.98
                          2013       1      246.360000  0.00     20.77
Eclipse Timing Variations 2008       4     9088.000000  0.00    261.44
                          2009       1    10220.000000  6.05      0.00
                          2010       4     8457.050000  0.00   1000.00
...                                ...             ...   ...       ...
Transit                   2014      93      756.948471  0.00   2070.00
Transit Timing Variations 2011       2      160.000000  0.00   2119.00
                          2012       2       57.011000  0.00    855.00
                          2013       2       22.339500  0.00    339.00
                          2014       3        0.000000  0.00      0.00

[69 rows x 4 columns]

In [201]:
planets.groupby("method")[["orbital_period"]].describe()

orbital_period                                \
                                       count           mean            std   
method                                                                       
Astrometry                               2.0     631.180000     544.217663   
Eclipse Timing Variations                9.0    4751.644444    2499.130945   
Imaging                                 12.0  118247.737500  213978.177277   
Microlensing                             7.0    3153.571429    1113.166333   
Orbital Brightness Modulation            3.0       0.709307       0.725493   
Pulsar Timing                            5.0    7343.021201   16313.265573   
Pulsation Timing Variations              1.0    1170.000000            NaN   
Radial Velocity                        553.0     823.354680    1454.926210   
Transit                                397.0      21.102073      46.185893   
Transit Timing Variations                3.0      79.783500      71.599884   

                                                                       \
                                       min          25%           50%   
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                                            
                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [202]:
df6 = pd.DataFrame({'groups': ['A', 'B', 'C', 'A', 'B', 'C','A', 'B', 'C'],
                   'var1': [10,23,33,22,11,99,40,20,15],
                   'var2': [100,253,333,262,111,969, 232,343,123]})
df6

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    40   232
7      B    20   343
8      C    15   123

In [203]:
df6.groupby("groups").mean()

var1        var2
groups                  
A       24.0  198.000000
B       18.0  235.666667
C       49.0  475.000000

In [204]:
df6.groupby("groups").agg([np.mean])

var1        var2
       mean        mean
groups                 
A        24  198.000000
B        18  235.666667
C        49  475.000000

In [205]:
df6

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    40   232
7      B    20   343
8      C    15   123

In [206]:
df6.groupby("groups").agg({"var1": ("mean", "median","sum"), 
                          "var2" : ("std", "var")
                                    })

var1                    var2               
       mean median  sum         std            var
groups                                            
A        24     22   72   86.185846    7428.000000
B        18     20   54  116.967232   13681.333333
C        49     33  147  440.513337  194052.000000

In [208]:
df6.groupby("groups").filter(lambda x : x["var1"].mean() > 19)

groups  var1  var2
0      A    10   100
2      C    33   333
3      A    22   262
5      C    99   969
6      A    40   232
8      C    15   123

In [210]:
df6[df6.var1 > 19]

groups  var1  var2
1      B    23   253
2      C    33   333
3      A    22   262
5      C    99   969
6      A    40   232
7      B    20   343

In [215]:
df6[["var1", "var2"]].transform(lambda x: (x-x.mean())/x.std() )

var1      var2
0 -0.738296 -0.762940
1 -0.266271 -0.187601
2  0.096826  0.113229
3 -0.302581 -0.153758
4 -0.701987 -0.721576
5  2.493263  2.504835
6  0.350993 -0.266570
7 -0.375200  0.150833
8 -0.556748 -0.676452

In [216]:
df6

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    40   232
7      B    20   343
8      C    15   123

In [6]:
ranarr = np.random.randint(0, 60, 48).reshape(6,8)
ranarr

array([[46, 25,  5, 27, 33, 44,  5, 33],
       [15, 55, 39, 15,  7, 15, 58, 49],
       [ 0, 34, 49, 15,  4, 51, 47, 48],
       [36, 15, 59, 51, 36, 20,  4, 50],
       [28, 50, 41, 31, 10, 38, 22, 12],
       [13, 40, 33, 50,  4, 43,  1, 19]])

In [8]:
np.reshape(ranarr, -1)

array([46, 25,  5, 27, 33, 44,  5, 33, 15, 55, 39, 15,  7, 15, 58, 49,  0,
       34, 49, 15,  4, 51, 47, 48, 36, 15, 59, 51, 36, 20,  4, 50, 28, 50,
       41, 31, 10, 38, 22, 12, 13, 40, 33, 50,  4, 43,  1, 19])

In [32]:
df["TotalPay"].min()

-618.13

In [33]:
df['EmployeeName'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].min()) | 
                   (df['TotalPayBenefits'] < df['TotalPayBenefits'].mean())]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...        
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [34]:
df['Id'][(df['TotalPayBenefits'] > df['TotalPayBenefits'].mean()) & (df['Year'] == 2012)].count()

20366