__22 Eylül 2021 - 1__

In [1]:
##https://www.trendyol.com/zepplin-giyim/python-yazilimci-siyah-tisort-p-44387247##

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [5]:
my_list = [1,2,3,4,5]
type(my_list)

list

In [6]:
my_array = np.array(my_list)

In [7]:
my_array

array([1, 2, 3, 4, 5])

In [8]:
type(my_array)

numpy.ndarray

In [9]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
a+b


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
AsumB = []
for i in range(len(a)):
    AsumB.append(a[i] + b[i])
AsumB

[7, 9, 11, 13, 15]

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

In [15]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
a-b

array([-5, -5, -5, -5, -5])

In [17]:
a.size

5

In [18]:
a.shape

(5,)

In [20]:
#number of dimention
a.ndim

1

In [21]:
a.dtype

dtype('int32')

In [22]:
a.itemsize

4

In [23]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [24]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
a1.size

12

In [27]:
a1.itemsize

4

In [28]:
a1.shape

(3, 4)

In [30]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [37]:
a3 = np.array([[[[[2,3,4,5],[1,2,4,5],[1,2,3,4]],[[2,3,4,5],[1,2,4,5],[1,2,3,4]], [[2,3,4,5],[1,2,4,5],[1,2,3,4]]]]])
a3

array([[[[[2, 3, 4, 5],
          [1, 2, 4, 5],
          [1, 2, 3, 4]],

         [[2, 3, 4, 5],
          [1, 2, 4, 5],
          [1, 2, 3, 4]],

         [[2, 3, 4, 5],
          [1, 2, 4, 5],
          [1, 2, 3, 4]]]]])

In [38]:
a3.shape

(1, 1, 3, 3, 4)

In [48]:
np.linspace(25,45,5, dtype = int)

array([25, 30, 35, 40, 45])

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones((5,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [63]:
np.ones((5,3)) + 7

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [64]:
np.ones((5,3)) / 0

<ipython-input-64-285746d23621>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.ones((5,3)) / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [69]:
np.full(4,3)

array([3, 3, 3, 3])

In [70]:
np.full(4,"sonsuz")

array(['sonsuz', 'sonsuz', 'sonsuz', 'sonsuz'], dtype='<U6')

In [78]:
np.full((32,32,3),255)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [89]:
b = np.arange(0,36)

In [90]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [91]:
b.reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [93]:
b.min()

0

In [94]:
b.max()

35

In [95]:
b.argmax()

35

In [96]:
b.argmin()

0

In [97]:
b.sum()

630

In [99]:
arr = np.arange(-4,5)

In [100]:
arr

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [101]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)>

In [104]:
a= np.arange(3,3,10)

In [105]:
a

array([], dtype=int32)

In [112]:
a=np.arange(2,10).replace(3,3)

AttributeError: 'numpy.ndarray' object has no attribute 'replace'