___PANDAS___

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [2]:
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [3]:
pd.DataFrame(data, columns = ["col1"])

col1
0     1
1     2
2     3
3     4
4     5

In [5]:
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data2 = np.arange(1,24,2).reshape(3,4)
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [7]:
pd.DataFrame(data2, columns = ["col1", "col2", "col3", "y"])

col1  col2  col3   y
0     1     3     5   7
1     9    11    13  15
2    17    19    21  23

In [9]:
df = pd.DataFrame(data2, columns = ["col1", "col2", "col3", "y"], index = ["a", "b", "c"])
df

col1  col2  col3   y
a     1     3     5   7
b     9    11    13  15
c    17    19    21  23

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.size

12

In [12]:
df.shape

(3, 4)

In [14]:
df.ndim

2

In [16]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [17]:
df.columns

Index(['col1', 'col2', 'col3', 'y'], dtype='object')

In [18]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [19]:
len(df)

3

In [20]:
df.keys()

Index(['col1', 'col2', 'col3', 'y'], dtype='object')

In [21]:
df.median()

col1     9.0
col2    11.0
col3    13.0
y       15.0
dtype: float64

In [22]:
df.col1

a     1
b     9
c    17
Name: col1, dtype: int32

In [23]:
df.col2

a     3
b    11
c    19
Name: col2, dtype: int32

In [24]:
df["col1"]

a     1
b     9
c    17
Name: col1, dtype: int32

In [25]:
df.xs

<bound method NDFrame.xs of    col1  col2  col3   y
a     1     3     5   7
b     9    11    13  15
c    17    19    21  23>

In [4]:
import numpy as np
s1 = np.random.randint(2,10, size = 40)
s1
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)

In [6]:
mydict = {"var1" : s1 , "var2" : s2, "var3": s3}
mydict

{'var1': array([8, 2, 6, 4, 7, 8, 8, 4, 5, 5, 5, 5, 5, 2, 7, 4, 8, 3, 9, 5, 8, 9,
        9, 2, 8, 5, 2, 4, 6, 9, 6, 5, 8, 7, 6, 7, 7, 5, 4, 5]),
 'var2': array([37, 60, 64, 85, 70, 93, 40, 31, 35, 43, 31, 66, 68, 48, 83, 43, 92,
        70, 55, 69, 73, 41, 62, 32, 46, 98, 60, 94, 32, 30, 83, 40, 93, 90,
        55, 93, 45, 62, 70, 97]),
 'var3': array([149, 102, 127, 142, 111, 144, 137, 105, 122, 123, 100, 100, 105,
        126, 105, 141, 140, 148, 147, 143, 113, 134, 104, 123, 140, 118,
        149, 115, 104, 123, 110, 148, 126, 115, 142, 134, 144, 108, 120,
        107])}

In [11]:
import pandas as pd
df_dict = pd.DataFrame(mydict)
df_dict

var1  var2  var3
0      8    37   149
1      2    60   102
2      6    64   127
3      4    85   142
4      7    70   111
5      8    93   144
6      8    40   137
7      4    31   105
8      5    35   122
9      5    43   123
10     5    31   100
11     5    66   100
12     5    68   105
13     2    48   126
14     7    83   105
15     4    43   141
16     8    92   140
17     3    70   148
18     9    55   147
19     5    69   143
20     8    73   113
21     9    41   134
22     9    62   104
23     2    32   123
24     8    46   140
25     5    98   118
26     2    60   149
27     4    94   115
28     6    32   104
29     9    30   123
30     6    83   110
31     5    40   148
32     8    93   126
33     7    90   115
34     6    55   142
35     7    93   134
36     7    45   144
37     5    62   108
38     4    70   120
39     5    97   107

In [13]:
df_dict[3:5]

var1  var2  var3
3     4    85   142
4     7    70   111

In [15]:
df_dict2 = df_dict[3:5]
df_dict2


var1  var2  var3
3     4    85   142
4     7    70   111

In [16]:
df_dict2.index = ["a","b"]
df_dict2

var1  var2  var3
a     4    85   142
b     7    70   111

In [17]:
df_dict2.columns = ["x","y","z"]
df_dict2

x   y    z
a  4  85  142
b  7  70  111

In [22]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [28]:
np.random.seed(101)
df3 = pd.DataFrame( np.random.randn(5,4),
                   index = "a b c d e".split(),
                   columns = "d f g h".split())
df3

d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [26]:
index = "a b c d e".split()

In [30]:
df3["d"]

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: d, dtype: float64

In [31]:
df3[["d"]]

d
a  2.706850
b  0.651118
c -2.018168
d  0.188695
e  0.190794

In [33]:
df3.loc[:,"d":"h"]

d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [34]:
df3.loc["b":"d","d":"h"]

d         f         g         h
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

In [35]:
df3

d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [41]:
df3["g"] * df3["f"]**2

a     0.358240
b    -0.086473
c     0.289674
d    -0.537439
e    10.203614
dtype: float64

In [42]:
df3["result"] = df3["g"] * df3["f"]**2 / df3["h"]
df3

d         f         g         h     result
a  2.706850  0.628133  0.907969  0.503826   0.711039
b  0.651118 -0.319318 -0.848077  0.605965  -0.142703
c -2.018168  0.740122  0.528813 -0.589001  -0.491806
d  0.188695 -0.758872 -0.933237  0.955057  -0.562730
e  0.190794  1.978757  2.605967  0.683509  14.928283

In [62]:
df3["result"] = df3["g"] * df3["f"].std() / df3["h"].mean()
df3

d         f         g         h    result
a  2.706850  0.628133  0.907969  0.503826  2.231464
b  0.651118 -0.319318 -0.848077  0.605965 -2.084270
c -2.018168  0.740122  0.528813 -0.589001  1.299634
d  0.188695 -0.758872 -0.933237  0.955057 -2.293563
e  0.190794  1.978757  2.605967  0.683509  6.404536

In [46]:
df3["h"].mean()

0.43187119296667903

In [71]:
#df3.drop("result", axis = 1) uygulandı. 
df3

d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [72]:
df3



d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [67]:
df3

d         f         g         h
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [75]:
np.random.seed(101)
df4 = pd.DataFrame( np.random.randn(5,4),
                   index = "a b c d e".split(),
                   columns = "w x y z".split())
df4

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [82]:
df4.loc["c" : "z"]

w         x         y         z
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [83]:
df4.loc["c" : "z" , "w"] 

c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [84]:
df4.loc["c" : "z" , "w" : "y"] 

w         x         y
c -2.018168  0.740122  0.528813
d  0.188695 -0.758872 -0.933237
e  0.190794  1.978757  2.605967

In [87]:
df4.loc["c" : "z"] [[ "w","y"]]

w         y
c -2.018168  0.528813
d  0.188695 -0.933237
e  0.190794  2.605967

In [91]:
df4.iloc[1:4,2:4]

y         z
b -0.848077  0.605965
c  0.528813 -0.589001
d -0.933237  0.955057

In [92]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [95]:
df3.iloc[:,2:]

y         z
a  0.907969  0.503826
b -0.848077  0.605965
c  0.528813 -0.589001
d -0.933237  0.955057
e  2.605967  0.683509

In [97]:
df3.iloc[1,2:] # pandas series olarak dönderdi

y   -0.848077
z    0.605965
Name: b, dtype: float64

>>en önemlisi bu dikkat

In [98]:
df3

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [100]:
df3 [  df3 ["x"] > 0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
e  0.190794  1.978757  2.605967  0.683509

In [103]:
df3 [  (df3 ["x"] > 0) & (df3 ["z"] > 0)]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [104]:
df3 [  (df3.x > 0) & (df3.z > 0)]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
e  0.190794  1.978757  2.605967  0.683509

In [106]:
df3[df3.x > 0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
c -2.018168  0.740122  0.528813 -0.589001
e  0.190794  1.978757  2.605967  0.683509

In [109]:
df3 [df3.z > 0] ["w"]

a    2.706850
b    0.651118
d    0.188695
e    0.190794
Name: w, dtype: float64

In [111]:
df3 [df3.z > 0]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [110]:
df3 [df3.z > 0] [["w"]]

w
a  2.706850
b  0.651118
d  0.188695
e  0.190794

In [112]:
df3 [df3.z > 0].iloc[2:5,:]

w         x         y         z
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509